/*
Generated by json2dart (https://github.com/billcoding/json2dart)
Created at 2024-01-12T17:13:32
-------------------------------------------------
{
  "id":100,
  "name": "halo",
  "idArr": [1],
  "nameArr": ["1"],
  "array0": {"aa":100,"bb": "halo"},
  "array1": [{"aa":100,"bb": "halo"}],
  "array2": [{"cc":{"aa":100,"bb": "halo"}}]
}
*/

class Json2Dart {
  final Json2DartArray0 array0;
  final List<Json2DartArray1> array1;
  final List<Json2DartArray2> array2;
  final int id;
  final List<int> idArr;
  final String name;
  final List<String> nameArr;

  const Json2Dart(this.array0, this.array1, this.array2, this.id, this.idArr, this.name, this.nameArr);

  factory Json2Dart.fromMap(Map<String, dynamic> m) {
    return Json2Dart(
      m.containsKey("array0") && m["array0"] != null ? m["array0"] : null,
      m.containsKey("array1") && m["array1"] != null ? m["array1"] : [],
      m.containsKey("array2") && m["array2"] != null ? m["array2"] : [],
      m.containsKey("id") && m["id"] != null ? m["id"] : 0,
      m.containsKey("idArr") && m["idArr"] != null ? m["idArr"] : [],
      m.containsKey("name") && m["name"] != null ? m["name"] : "",
      m.containsKey("nameArr") && m["nameArr"] != null ? m["nameArr"] : [],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "array0": array0,
      "array1": array1,
      "array2": array2,
      "id": id,
      "idArr": idArr,
      "name": name,
      "nameArr": nameArr,
    };
  }

  String toJson() {
    return '{"array0":$array0, "array1":$array1, "array2":$array2, "id":$id, "idArr":$idArr, "name":$name, "nameArr":$nameArr}';
  }

  @override
  String toString() {
    return '{array0: $array0, array1: $array1, array2: $array2, id: $id, idArr: $idArr, name: $name, nameArr: $nameArr}';
  }
}

class Json2DartArray0 {
  final int aa;
  final String bb;

  const Json2DartArray0(this.aa, this.bb);

  factory Json2DartArray0.fromMap(Map<String, dynamic> m) {
    return Json2DartArray0(
      m.containsKey("aa") && m["aa"] != null ? m["aa"] : 0,
      m.containsKey("bb") && m["bb"] != null ? m["bb"] : "",
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "aa": aa,
      "bb": bb,
    };
  }

  String toJson() {
    return '{"aa":$aa, "bb":$bb}';
  }

  @override
  String toString() {
    return '{aa: $aa, bb: $bb}';
  }
}

class Json2DartArray1 {
  final int aa;
  final String bb;

  const Json2DartArray1(this.aa, this.bb);

  factory Json2DartArray1.fromMap(Map<String, dynamic> m) {
    return Json2DartArray1(
      m.containsKey("aa") && m["aa"] != null ? m["aa"] : 0,
      m.containsKey("bb") && m["bb"] != null ? m["bb"] : "",
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "aa": aa,
      "bb": bb,
    };
  }

  String toJson() {
    return '{"aa":$aa, "bb":$bb}';
  }

  @override
  String toString() {
    return '{aa: $aa, bb: $bb}';
  }
}

class Json2DartArray2 {
  final Json2DartArray2Cc cc;

  const Json2DartArray2(this.cc);

  factory Json2DartArray2.fromMap(Map<String, dynamic> m) {
    return Json2DartArray2(
      m.containsKey("cc") && m["cc"] != null ? m["cc"] : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "cc": cc,
    };
  }

  String toJson() {
    return '{"cc":$cc}';
  }

  @override
  String toString() {
    return '{cc: $cc}';
  }
}

class Json2DartArray2Cc {
  final int aa;
  final String bb;

  const Json2DartArray2Cc(this.aa, this.bb);

  factory Json2DartArray2Cc.fromMap(Map<String, dynamic> m) {
    return Json2DartArray2Cc(
      m.containsKey("aa") && m["aa"] != null ? m["aa"] : 0,
      m.containsKey("bb") && m["bb"] != null ? m["bb"] : "",
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "aa": aa,
      "bb": bb,
    };
  }

  String toJson() {
    return '{"aa":$aa, "bb":$bb}';
  }

  @override
  String toString() {
    return '{aa: $aa, bb: $bb}';
  }
}
