/*
Generated by json2dart (https://github.com/billcoding/json2dart)
Created at 2024-01-12T18:22:02
-------------------------------------------------
{
  "code": 200,
  "ddd": [{"wow": 1000}],
  "data": {
    "d": [
      1,
      2,
      3,
      4
    ]
  }
}
*/

class Json2Dart {
  final int code;
  final Json2DartData data;
  final List<Json2DartDdd> ddd;

  const Json2Dart(this.code, this.data, this.ddd);

  factory Json2Dart.fromMap(Map<String, dynamic> m) {
    return Json2Dart(
      m.containsKey("code") && m["code"] != null ? m["code"]: 0,
      m.containsKey("data") && m["data"] != null ? m["data"]: null,
      m.containsKey("ddd") && m["ddd"] != null ? (m["ddd"] as List<dynamic>).map((a) => a as Map<String, dynamic>).map((a) => Json2DartDdd.fromMap(a)).toList(): [],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "code": code,
      "data": data,
      "ddd": ddd,
    };
  }

  String toJson() {
    return '{"code":$code, "data":$data, "ddd":$ddd}';
  }

  @override
  String toString() {
    return '{code: $code, data: $data, ddd: $ddd}';
  }
}

class Json2DartData {
  final List<int> d;

  const Json2DartData(this.d);

  factory Json2DartData.fromMap(Map<String, dynamic> m) {
    return Json2DartData(
      m.containsKey("d") && m["d"] != null ? (m["d"] as List<dynamic>).map((a) => a as List<int>}).toList(): [],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "d": d,
    };
  }

  String toJson() {
    return '{"d":$d}';
  }

  @override
  String toString() {
    return '{d: $d}';
  }
}

class Json2DartDdd {
  final int wow;

  const Json2DartDdd(this.wow);

  factory Json2DartDdd.fromMap(Map<String, dynamic> m) {
    return Json2DartDdd(
      m.containsKey("wow") && m["wow"] != null ? m["wow"]: 0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      "wow": wow,
    };
  }

  String toJson() {
    return '{"wow":$wow}';
  }

  @override
  String toString() {
    return '{wow: $wow}';
  }
}
